### ISSUE TITLE
error getting index file fdroid

### ISSUE THREAD

**Issue by aravinthu** [androportal/f-droid-fdroidserver#2]
trying connect fdroid server with client, i followed ur steps. still getting error.

**Comment by psachin** [comment]
Can you elaborate on:
- In which step you are encountering the error?
- What is the error?

This repo is quite old and not maintained. However I'll see if I can help.

**Comment by aravinthu** [comment]
over all settings looks good, but when i tring to connect the repo from f-droid android client. 

i'm getting this message "error getting index file". 

and i followed this info also https://f-droid.org/wiki/index.php?title=Installing_the_Server_and_Repo_Tools

**Comment by psachin** [comment]
Can you confirm if `index.html` file exist inside `/var/www/fdroid/` ? and it has proper permissions?

**Comment by psachin** [comment]
May be the file name is `index.php`(I'm not sure), as I see `wp-*`. Also o/p of `curl` to localhost would be helpful.

**Comment by aravinthu** [comment]
Now it's intex.xml and index.jar

Can you please elabrate this step (from your guide)
Setting system's PATH

Adding fdroid binary in system's $PATH

for example

export PATH=/path/to/this/repo/:$PATH
Or you can add the same line in your .bashrc file.

**Comment by psachin** [comment]
`/path/to/this/repo/` means the absolute path where you have cloned this repo(f-droid-fdroidserver). It can be `/home/aravinthu/f-droid-fdroidserver` or whatever your username is.

Which transforms to

`
export PATH=/home/aravinthu/f-droid-fdroidserver/:$PATH
`
